// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgRpq4pSJ0f7qQIPyakfrbrC6WMtbCtKE',
    appId: '1:444330951212:ios:c2dce703b2c2c48db50789',
    messagingSenderId: '444330951212',
    projectId: 'tripthread-app-21bbf',
    storageBucket: 'tripthread-app-21bbf.firebasestorage.app',
    iosClientId: '444330951212-2rf5l779p2i06p2f79pv466glr87nohu.apps.googleusercontent.com',
    iosBundleId: 'com.tripthread.tripthread',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgRpq4pSJ0f7qQIPyakfrbrC6WMtbCtKE',
    appId: '1:444330951212:ios:c2dce703b2c2c48db50789',
    messagingSenderId: '444330951212',
    projectId: 'tripthread-app-21bbf',
    storageBucket: 'tripthread-app-21bbf.firebasestorage.app',
    iosClientId: '444330951212-2rf5l779p2i06p2f79pv466glr87nohu.apps.googleusercontent.com',
    iosBundleId: 'com.tripthread.tripthread',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU3jWSGITQeLAaFoqQAul66tL0jGXzRrM',
    appId: '1:444330951212:web:2465da57e17c7ebdb50789',
    messagingSenderId: '444330951212',
    projectId: 'tripthread-app-21bbf',
    authDomain: 'tripthread-app-21bbf.firebaseapp.com',
    storageBucket: 'tripthread-app-21bbf.firebasestorage.app',
    measurementId: 'G-V2Q80R1TE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJNbwzXMO7scCbAEvz_VJTnkepWGzxBr8',
    appId: '1:444330951212:android:30a76737cda1b847b50789',
    messagingSenderId: '444330951212',
    projectId: 'tripthread-app-21bbf',
    storageBucket: 'tripthread-app-21bbf.firebasestorage.app',
  );
}
